### PR TITLE
Use sale proprietary name to fix #1

### LINKED ISSUE #1: Consumer-friendly names for USA
@grahamegrieve are you OK if we update to make the US-based names consistent with the "Sale Proprietary Name" values at https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html? And if you are ... let me know if you'd rather I submit a PR or if you want to do this (I'm not sure if you've hand-authored the .JSON file or generated it from another source)

### PR DESCRIPTION
**Pull request by jmandel**

### CODE REVIEW

**Comment by grahamegrieve** [comment]
why Jannsen and not others? 
Should the different pfizer codes get different consumer names? 
I'll have to think about the Australian consumer names.

**Comment by jmandel** [comment]
> why Jannsen and not others?


How so? I attempted to populate all the "en-US" consumer friendly names with values from "Sale Proprietary Name" at https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html

**Comment by jmandel** [comment]
Or, why did I add `212` to the value set? Because it's a currently authorized product being administered in USA...

**Comment by grahamegrieve** [comment]
yes. why add just 212. For US use, the value set should include any vaccine recognised in USA, right? That's a more extensive list than the list authorised for use. See https://www.cdc.gov/coronavirus/2019-ncov/travelers/proof-of-vaccination.html

**Comment by jmandel** [comment]
Sure, we can have a separate discussion about how to make the list complete (I'm not trying to suggest we exercise any discretion here; populating the full CVX set seems like the right move). To start I just wanted to get sales proprietary names aligned, and will track expanding the valueset in #3.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
