### PR TITLE
add additional COVID codes as labeled by the CDC

### PR DESCRIPTION
**Pull request by sorech02**
Nathan Bunker asked me to look at this file and see if we could automate updates to it as the CDC adds codes.  For this pass, I added only COVID codes that were not NOS types.  

I took the CVX Short Description as the "display" and the Product Tradename as the "consumer-friendly".

Happy to take any feedback.

### CODE REVIEW

**Comment by grahamegrieve** [comment]
Adding 510, 511, 211, 219 - all make sense. But why not others? Does "NOS" mean Not otherwise specified? Why not 502?

**Comment by sorech02** [comment]
> Why not 502?

This was my error.  I was using a file from October, and this was approved in November, so I didn't see it.

> But why not others? Does "NOS" mean Not otherwise specified?

My apologies for not defining terms.  When I say "NOS", I do mean Not Otherwise Specified, which are generic codes that exist across the CVX codes separate from the COVID application here.

My strategy in this Pull was to take any CVX that I had a link to a manufacturer, and therefore their Tradename for use in the "consumer-friendly" value.  However, upon looking again today, I see that this strategy is questionable because of the many Non-US vaccines where this link doesn't exist in the CDC data.

* CVX 501, 503-509 could also be added with a policy for how to source a friendly name; these are codes for specific products.
* CVX 213, 500 are the NOS codes, which represent unknown products; a trade name will never exist for these.

I could add any of these with the short description for the "friendly" value.  Open to other options.

**Comment by grahamegrieve** [comment]
using NOS as a term is generally OK, but I wasn't sure because you omitted 502 and other non-US recognised vaccines without stating that. So I thought I'd check. I think it's ok to add only US recognised vaccines for now, and let some other entity actually using a code figure out the naming issues. if you're ok with that, I can approve the PR

**Comment by nathanbunker** [comment]
I'm good with merging what is proposed now. 

For the master set of vaccine codes I agree that is ideal to the entities that are giving the vaccination define the codes, and not use the US CDC 500 codes for that. 

However, we may need to add them to a CVX specific set so that we can put the mapping from the international values in our primary set back to CVX for US-based sites. We are working on a preliminary mapping of CVX to SMOMED and ICD-11 and back again. We hope to have that by January to get feedback on.

We probably need to create a set of files with different levels of information. I'll try to put some thought to that and put a proposal together. For now Chris will just update this file with US only codes until we figure out where 500's should go.

**Comment by grahamegrieve** [comment]
I think that the other parties will have real reasons to use CVX, so we'll let them decide about that. But there is ample reason to include 5xx codes for vaccines recognised by USA (as this PR does). So I'll merge that, and we'll see what develops. 

I'll look forward to seeing the mapping coming forward.

**Pull request merged**
